### ISSUE TITLE
FYI - may want to fix link to app in wiki page for "use app" 

### ISSUE THREAD

**Issue by daauerbach** [avelez-espino/Ck-ForecastR-Releases#21]
Thanks for this work. As I'm checking it out, I noticed the wiki currently has a typo in the url targeted by the text `shiny app`...

**Comment by SOLV-Code** [comment]
Hi Dan,
thank you for letting us know. We'll try to fix this over the next few days.
Cheers,
Gottfried

**Comment by SOLV-Code** [comment]
Hi Dan, 
I looked through the wiki, but couldn't find the broken link. Could you please point me to the specific page?

Cheers,
Gottfried

**Comment by daauerbach** [comment]
Looks fixed to me...

Thanks again for the efforts here. It seems like there’s plenty of good feedback in a couple of the issues threads, and it’ll be interesting to see how this continues to evolve.

**Comment by SOLV-Code** [comment]
Hi Dan,

Thank you. I did go through and tweak a few things. Glad that fixed it. 
Please continue to send anything that you notice our way, from small edits to substantive suggestions on the interface, statistical methods, or extensions you'd like to see in the future.

Cheers,
Gottfried
